CREATE TABLE IF NOT EXISTS jobs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        datum DATE NOT NULL,
        time_start TIME,
        time_end TIME,
        pause REAL DEFAULT 0,
        arbeitsstunden REAL NOT NULL,
        taetigkeitsbeschreibung TEXT NOT NULL,
        machine_used INTEGER DEFAULT NULL,
        maschinenstunden REAL DEFAULT NULL,
        status TEXT DEFAULT 'erfasst',
        rejection_reason TEXT,
        checked_time TIMESTAMP,
        checked_by INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES user (id),
        FOREIGN KEY (checked_by) REFERENCES user (id),
        FOREIGN KEY (machine_used) REFERENCES machines (id)
);