CREATE TABLE IF NOT EXISTS jobs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        user_id INTEGER NOT NULL,
        date DATE NOT NULL,
        time_start TIME,
        time_end TIME,
        pause_hours REAL DEFAULT 0,
        work_hours REAL NOT NULL,
        work_comment TEXT NOT NULL,
        machine_id INTEGER DEFAULT NULL,
        machine_hours REAL DEFAULT NULL,
        status TEXT DEFAULT 'erfasst',
        rejection_reason TEXT,
        checked_time TIMESTAMP,
        checked_by INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES user (id),
        FOREIGN KEY (checked_by) REFERENCES user (id),
        FOREIGN KEY (machine_id) REFERENCES machines (id)
);